<?php

namespace App\DataFixtures;

use App\Entity\Tank;
use App\Entity\Garage;
use App\Entity\Usine;
use App\Entity\Member;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;



class AppFixtures extends Fixture
{
    private const IS_3 = 'IS-3';
    private const KV_1 = 'KV-1';
    private const FT_17 = 'FT-17';

    private const GARAGE_RUSSE = 'garage-russe-1';
    private const GARAGE_FRANCAIS = 'garage-français-1';

    private const DONALD_TRUMP = 'premier_acheteur';

    private const USINE_SECRET = 'Usine_secret';
    private const USINE_NOT_SO_SECRET = 'Usine_not_so_secret';


    /**
     * Generates initialization data for member : [name, description]
     * @return \\Generator
     */
    private static function memberDataGenerator()
    {
        yield ["Donald TRUMP", "former US president", self::DONALD_TRUMP];;
    }

    /**
     * Generates initialization data for garage : [name, capacity]
     * @return \\Generator
     */
    private static function usineDataGenerator()
    {
        yield ["Usine privée", "cette usine est secrete", false, self::USINE_SECRET, self::DONALD_TRUMP, self::IS_3];
        yield ["Usine publique", "cette usine n'est pas secrete", true, self::USINE_NOT_SO_SECRET, self::DONALD_TRUMP, self::IS_3];
    }

    /**
     * Generates initialization data for garage : [name, capacity]  
     * @return \\Generator
     */
    private static function garageDataGenerator()
    {
        yield ["garage de chars russes", 5, self::GARAGE_RUSSE, self::DONALD_TRUMP];
        yield ["garage de chars français", 4, self::GARAGE_FRANCAIS, self::DONALD_TRUMP];
    }

    /**
     * Generates initialization data for tank : [name, year, origine, value, weight]
     * @return \\Generator
     */
    private static function tanksGenerator()
    {
        yield [self::GARAGE_RUSSE, self::IS_3, 1950, "russe", 6, 49000];
        yield [self::GARAGE_RUSSE, self::KV_1, 1939, "russe", 4, 43000];
        yield [self::GARAGE_FRANCAIS, self::FT_17, 1917, "français", 4, 7000];
    }

    public function load(ObjectManager $manager)
    {
        $inventoryRepo = $manager->getRepository(Garage::class);
        
        foreach (self::memberDataGenerator() as [$name, $description, $memberReference] ) {
            $member = new Member();
            $member->setName($name);
            $member->setDescription($description);
            $manager->persist($member);
            $manager->flush();

            // Once the member instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($memberReference, $member);
        }

        foreach (self::garageDataGenerator() as [$name, $capacity, $garageReference, $memberReference] ) {
            $garage = new Garage();
            $garage->setName($name);
            $garage->setCapacity($capacity);

            $this->getReference($memberReference)->addGarage($garage);

            $manager->persist($garage);
            $manager->flush();

            // Once the Garage instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($garageReference, $garage);
        }

        foreach (self::usineDataGenerator() as [$name, $description, $public, $usineReference, $memberReference] ) {
            $usine = new Usine();
            $usine->setName($name);
            $usine->setDescription($description);   
            $usine->setPublic($public);

            $this->getReference($memberReference)->addUsine($usine);
           
            $manager->persist($usine);
            $manager->flush();

            // Once the member instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($usineReference, $usine);
        }

        foreach (self::tanksGenerator() as [$garageReference, $name, $year, $origine, $value, $weight])
        {
            // Retrieve the One-side instance of Gargae from its reference name
            $garage = $this->getReference($garageReference);
            $tank = new Tank();
            $tank->setName($name);
            $tank->setValue($value);
            $tank->setYear($year);
            $tank->setOrigine($origine);
            $tank->setWeight($weight);
            // Add the Many-side Tank to its containing garage
            $garage->addTank($tank);
            

            // Requir that the ORM\OneToMany attribute on Garage::tanks has "cascade: ['persist']"
            $manager->persist($garage);

        }           
        $manager->flush();
    }
}

